create table offers
(
    ID_Offer     int auto_increment
        primary key,
    ID_User      int                                                         not null,
    ID_Car       int                                                         null,
    Availability enum ('available', 'unavailable')       default 'available' not null,
    City         varchar(100)                                                null,
    Date_Start   date                                                        not null,
    Date_End     date                                                        not null,
    Hour_Start   time                                                        not null,
    Hour_End     time                                                        not null,
    Description  longtext                                                    null,
    isVIP        enum ('noVIP', '1WeekVIP', '2WeeksVIP') default 'noVIP'     not null,
    constraint offers_cars_ID_Car_fk
        foreign key (ID_Car) references cars (ID_Car),
    constraint offers_ibfk_2
        foreign key (ID_User) references users (ID_User)
)
    engine = InnoDB
    charset = utf8mb4;

create index ID_User
    on offers (ID_User);

INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (1, 1, 1, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (10, 3, 3, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (11, 1, 4, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (12, 4, 5, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (13, 2, 6, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (14, 2, 7, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (15, 3, 8, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (16, 1, 9, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (17, 1, 10, 'available', null, '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (18, 1, 24, 'available', 'TANGER', '2021-06-09', '2021-06-23', '13:16:00', '14:16:00', ' ', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (19, 1, 25, 'available', 'TANGER', '2021-06-09', '2021-06-23', '13:16:00', '14:16:00', ' ', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (20, 1, 26, 'available', 'TETOUAN', '2021-06-02', '2021-06-02', '14:20:00', '14:20:00', ' ', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (25, 1, 31, 'available', 'TETOUAN', '2021-06-02', '2021-06-02', '14:20:00', '14:20:00', ' ', 'noVIP');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, City, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (26, 1, 32, 'available', 'TANGER', '2021-06-16', '2021-06-20', '14:23:00', '14:26:00', ' ', 'noVIP');