create table offers
(
    ID_Offer     int auto_increment
        primary key,
    ID_User      int                                                   not null,
    ID_Car       int                                                   null,
    Availability enum ('available', 'unavailable') default 'available' not null,
    Date_Start   date                                                  not null,
    Date_End     date                                                  not null,
    Hour_Start   time                                                  not null,
    Hour_End     time                                                  not null,
    Description  longtext                                              null,
    isVIP        enum ('novip', '1weekvip', '2weeksvip')               null
);

create index ID_User
    on offers (ID_User);

INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (10, 3, 3, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', '1weekvip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (11, 1, 4, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', '1weekvip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (12, 4, 5, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (13, 2, 6, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (14, 2, 7, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (15, 3, 8, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (16, 1, 9, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (17, 1, 10, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', '1weekvip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (1, 1, 1, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (18, 1, 24, 'available', '2021-06-09', '2021-06-23', '13:16:00', '14:16:00', ' ', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (19, 1, 25, 'available', '2021-06-09', '2021-06-23', '13:16:00', '14:16:00', ' ', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (20, 1, 26, 'available', '2021-06-02', '2021-06-02', '14:20:00', '14:20:00', ' ', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (25, 1, 31, 'available', '2021-06-02', '2021-06-02', '14:20:00', '14:20:00', ' ', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (26, 1, 32, 'available', '2021-06-16', '2021-06-20', '14:23:00', '14:26:00', ' ', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (27, 1, 11, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (28, 1, 12, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (29, 1, 13, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (30, 1, 14, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (31, 1, 15, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', '1weekvip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (32, 1, 16, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (33, 1, 17, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (34, 1, 18, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (35, 1, 19, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (36, 1, 20, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (37, 1, 21, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (38, 1, 22, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', '1weekvip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (39, 1, 23, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', 'novip');
INSERT INTO neirautorental.offers (ID_Offer, ID_User, ID_Car, Availability, Date_Start, Date_End, Hour_Start, Hour_End, Description, isVIP) VALUES (40, 3, 2, 'available', '2021-05-18', '2021-05-15', '10:00:00', '23:00:00', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut eros quis urna mattis gravida sed vel tellus. Fusce vitae tincidunt justo, eu placerat sem. Sed fringilla orci sit amet blandit molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam pretium, nibh non venenatis ultrices, neque velit pulvinar libero', '1weekvip');